services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: tnvc_admin
      POSTGRES_PASSWORD: 1212
      POSTGRES_DB: tnvc_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always

volumes:
  pgdata:
    driver: local

